/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/AxaRYko3iX9
 */
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Checkbox } from "@/components/ui/checkbox"
import { Label } from "@/components/ui/label"

export function MainComponent() {
  return (
    (<div
      className="flex flex-col items-center justify-center min-h-screen bg-gray-100 dark:bg-gray-900">
      <header
        className="mb-10 flex justify-between w-full max-w-md mx-auto px-4 md:px-6">
        <h1 className="text-4xl font-bold text-gray-900 dark:text-gray-100">Todo App</h1>
        <Button className="ml-auto" variant="outline">
          Connect Wallet
        </Button>
      </header>
      <main className="w-full max-w-md mx-auto">
        <div className="bg-white dark:bg-gray-800 shadow rounded-lg p-6">
          <form className="space-y-4">
            <Input className="w-full" id="new-task" placeholder="Add a new task" type="text" />
            <Button className="w-full" type="submit">
              Add Task
            </Button>
          </form>
          <ul className="mt-4 space-y-4">
            <li className="flex items-center justify-between">
              <div className="flex items-center space-x-2">
                <Checkbox id="task-1" />
                <Label className="text-gray-900 dark:text-gray-100" htmlFor="task-1">
                  Buy groceries
                </Label>
              </div>
              <Button size="icon" variant="outline">
                <TrashIcon className="h-4 w-4" />
                <span className="sr-only">Delete task</span>
              </Button>
            </li>
            <li className="flex items-center justify-between">
              <div className="flex items-center space-x-2">
                <Checkbox id="task-2" />
                <Label className="text-gray-900 dark:text-gray-100" htmlFor="task-2">
                  Finish project
                </Label>
              </div>
              <Button size="icon" variant="outline">
                <TrashIcon className="h-4 w-4" />
                <span className="sr-only">Delete task</span>
              </Button>
            </li>
            <li className="flex items-center justify-between">
              <div className="flex items-center space-x-2">
                <Checkbox id="task-3" />
                <Label className="text-gray-900 dark:text-gray-100" htmlFor="task-3">
                  Read a book
                </Label>
              </div>
              <Button size="icon" variant="outline">
                <TrashIcon className="h-4 w-4" />
                <span className="sr-only">Delete task</span>
              </Button>
            </li>
          </ul>
          <Button className="w-full mt-6" variant="outline">
            Clear All
          </Button>
        </div>
      </main>
    </div>)
  );
}


function TrashIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M3 6h18" />
      <path d="M19 6v14c0 1-1 2-2 2H7c-1 0-2-1-2-2V6" />
      <path d="M8 6V4c0-1 1-2 2-2h4c1 0 2 1 2 2v2" />
    </svg>)
  );
}
